DROP TABLE IF EXISTS "tb_album";
CREATE TABLE "public"."tb_album" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nome_album" character varying(255) NOT NULL,
    CONSTRAINT "tb_album_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

DROP TABLE IF EXISTS "tb_arquivo";
CREATE TABLE "public"."tb_arquivo" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "bucket" character varying(255),
    "content_type" character varying(255),
    "descricao" character varying(255),
    "extensao" character varying(255),
    "nome_arquivo" character varying(255),
    "object_name" character varying(255),
    "tamanho_bytes" bigint,
    "uuid" uuid NOT NULL,
    "album_id" bigint,
    CONSTRAINT "tb_arquivo_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "uksxkrrt963cbpma5re1e6r4ybf" UNIQUE ("uuid")
) WITH (oids = false);


DROP TABLE IF EXISTS "tb_artista";
CREATE TABLE "public"."tb_artista" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nome_artista" character varying(255) NOT NULL,
    CONSTRAINT "tb_artista_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "tb_artista_album";
CREATE TABLE "public"."tb_artista_album" (
    "album_id" bigint NOT NULL,
    "artista_id" bigint NOT NULL
) WITH (oids = false);


ALTER TABLE ONLY "public"."tb_arquivo" ADD CONSTRAINT "fkeshdkxtcugaajcga8w2qsyyso" FOREIGN KEY (album_id) REFERENCES tb_album(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."tb_artista_album" ADD CONSTRAINT "fkg8skej0wgqmvvmqr6fgf3kl45" FOREIGN KEY (album_id) REFERENCES tb_album(id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."tb_artista_album" ADD CONSTRAINT "fks04mf1mgq0bxyj81l50d8gi5e" FOREIGN KEY (artista_id) REFERENCES tb_artista(id) NOT DEFERRABLE;