DROP TABLE IF EXISTS "tb_usuario_role";
DROP TABLE IF EXISTS "tb_role";
DROP TABLE IF EXISTS "tb_usuario";

CREATE TABLE "public"."tb_usuario" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nome" character varying(255) NOT NULL, -- Este será o login
    "senha" character varying(255) NOT NULL,
    CONSTRAINT "tb_usuario_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "uk_usuario_nome" UNIQUE ("nome")
) WITH (oids = false);

CREATE TABLE "public"."tb_role" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nome_role" character varying(50) NOT NULL, -- Ex: 'ROLE_USER', 'ROLE_ADMIN'
    CONSTRAINT "tb_role_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE TABLE "public"."tb_usuario_role" (
    "usuario_id" bigint NOT NULL,
    "role_id" bigint NOT NULL,
    CONSTRAINT "tb_usuario_role_pkey" PRIMARY KEY ("usuario_id", "role_id"),
    CONSTRAINT "fk_usuario" FOREIGN KEY ("usuario_id") REFERENCES "public"."tb_usuario"("id"),
    CONSTRAINT "fk_role" FOREIGN KEY ("role_id") REFERENCES "public"."tb_role"("id")
);

